apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mavenwebappdep
  namespace: {{ .Values.namespace | default "ns1" }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mavenwebapp
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mavenwebapp
    spec:
      containers:
      - name: mavenwebapp
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
